
--==========================================HEALTHCARE DATA ANALYTICS=================================--

drop table if exists health

create table health (
         SNO	numeric,
		 "MRD No."	numeric,
		 "D.O.A"	varchar(20),
		 "D.O.D"	varchar(10),
		 AGE	numeric,
		 GENDER	varchar(8),
		 RURAL	varchar(4),
		 "TYPE OF ADMISSION-EMERGENCY/OPD" varchar(10),	
		 "month year" varchar(10),
		 "DURATION OF STAY" numeric,
		 "duration of intensive unit stay " numeric,	
		 OUTCOME varchar(99),
		 SMOKING numeric,
		 ALCOHOL numeric,
		 DM numeric,
		 HTN numeric,
		 CAD numeric,
		 "PRIOR CMP" numeric,
		 CKD numeric,
		 HB  varchar(10),
		 TLC  varchar(10),
		 PLATELETS  varchar(10),
		 GLUCOSE  varchar(10),
		 UREA	 varchar(10),
		 CREATININE  varchar(10),
		 BNP  varchar(10),
		 RAISED_CARDIAC_ENZYMES  numeric,	
		 EF  varchar(10),
		 SEVERE_ANAEMIA  numeric,
		 ANAEMIA  numeric,
		 "STABLE ANGINA"  numeric,
		 ACS  numeric,
		 STEMI  numeric,
		 ATYPICAL_CHEST_PAIN  numeric,
		 HEART_FAILURE  numeric,
		 HFREF  numeric,
		 HFNEF  numeric,
		 VALVULAR  numeric,
		 CHB	 numeric,
		 SSS	 numeric,
		 AKI  numeric,
		 CVA_INFRACT  numeric,
		 CVA_BLEED  numeric,
		 AF  numeric,
		 VT	  numeric,
		 PSVT  numeric,
		 CONGENITAL  numeric,
		 UTI  numeric,
		 NEURO_CARDIOGENIC_SYNCOPE  numeric,
		 ORTHOSTATIC  numeric,
		 INFECTIVE_ENDOCARDITIS  numeric,
		 DVT	 numeric,
		 CARDIOGENIC_SHOCK  numeric,
		 SHOCK  numeric,
		 PULMONARY_EMBOLISM  numeric,	
		 CHEST_INFECTION varchar(3)

)

-- Sample data
select * from health


--==========================================CLEANING DATA-REMOVING DUPLICATES=========================================--

--Creating a view from clean_data
create or replace view vw_health as
--Creating a CTE (temp table) called 'clean_data' ,to extract non-duplicate data
with clean_data as(
--selecting all the data to identify  duplicates using 'duplicate _number' column generated by window function
select *,
      row_number() over(partition by "MRD No.","D.O.A","D.O.D" order by "MRD No.") duplicate_number
from health
--order by "MRD No."
)
--select non-duplicate data
select * from clean_data
where duplicate_number=1 and "MRD No." is not null
--order by "MRD No."

--=========================================BUSINESS PROBLEMS=====================================--

select * from vw_health

--1.Total discharges
select count(*) as no_of_discharges
from vw_health
where outcome='DISCHARGE'

--2.Average daily discharge rate
--It is total discharges divided by the total length of stay
select round(
   (select count(*) as no_of_discharges
   from vw_health
   where outcome='DISCHARGE')/(select sum("DURATION OF STAY") as total_length_of_stay
   from vw_health),2)*100 ||'%' as Avg_daily_discharge_rate

   --(or by avoiding subquery)
select 
      round(
	  sum(case when outcome='DISCHARGE' then 1.0 else 0.0 end)/
	  sum("DURATION OF STAY"),2)*100 ||'%' as avg_daily_discharge_rate
from vw_health

--3.Average length of stay
--Total length of stay by total discharges
select 
      round(
      sum("DURATION OF STAY")/sum(case when outcome='DISCHARGE' then 1.0 else 0.0 end),0)
      as avg_length_of_stay
from vw_health

--4.Distribution of discharges by age group
--<16 paediatric
--16-55 adult
-->=55 senior citizen
select
      case 
	      when age<16 then 'paediatric'
		  when age<55 then 'adult'
		  when age>=55 then 'senior_citizen'
		  else 'unknown'
		  end 
		  as age_group,count(*)as age_distribution
from vw_health
where outcome='DISCHARGE'
group by age_group
order by age_distribution desc

--5.Distribution of discharges by gender
select
      gender,count(*)as gender_distribution
from vw_health
where outcome='DISCHARGE'
group by gender
order by gender_distribution desc

--6.Distribution of discharges by day of the week
select
    to_char(
        to_date("D.O.D",'MM/DD/YYYY'),
        'FMDay'
    ) as day_of_week,
    count(*) as day_distribution
from vw_health
where outcome='DISCHARGE'
  and "D.O.D" ~ '^\d{1,2}/\d{1,2}/\d{4}$'
group by 1
order by 2 desc;

